package org.lskk.lumen.reasoner.social;

import org.hibernate.annotations.Type;
import org.joda.time.DateTime;
import org.lskk.lumen.core.SimpleTruthValue;
import org.lskk.lumen.reasoner.event.AgentResponse;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Created by ceefour on 19/11/2015.
 */
@Entity
@Table(schema = "lumen")
public class SocialJournal implements Serializable {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column(columnDefinition = "timestamp with time zone", nullable = false)
    @Type(type = "org.jadira.usertype.dateandtime.joda.PersistentDateTime")
    private DateTime creationTime;
    private String agentId;
    private String avatarId;
    private String socialChannelId;
    @Column(columnDefinition = "text")
    private String receivedText;
    private SimpleTruthValue truthValue;
    @Column(columnDefinition = "text")
    private String responseText;
    @Column
    private String responseKind;
    @Column(columnDefinition = "text")
    private String responseInsertables;
    private Float processingTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public DateTime getCreationTime() {
        return creationTime;
    }

    public void setCreationTime(DateTime creationTime) {
        this.creationTime = creationTime;
    }

    /**
     * e.g. arkan
     * @return
     */
    public String getAgentId() {
        return agentId;
    }

    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * e.g. nao1
     * @return
     */
    public String getAvatarId() {
        return avatarId;
    }

    public void setAvatarId(String avatarId) {
        this.avatarId = avatarId;
    }

    /**
     * e.g. direct, avatar, facebook, twitter
     * @return
     */
    public String getSocialChannelId() {
        return socialChannelId;
    }

    public void setSocialChannelId(String socialChannelId) {
        this.socialChannelId = socialChannelId;
    }

    public String getReceivedText() {
        return receivedText;
    }

    public void setReceivedText(String receivedText) {
        this.receivedText = receivedText;
    }

    /**
     * Truth value of the matching AIML {@link org.lskk.lumen.reasoner.aiml.Category}.
     * @return
     */
    public SimpleTruthValue getTruthValue() {
        return truthValue;
    }

    public void setTruthValue(SimpleTruthValue truthValue) {
        this.truthValue = truthValue;
    }

    /**
     * Immediate response generated by AIML.
     * @return
     */
    public String getResponseText() {
        return responseText;
    }

    public void setResponseText(String responseText) {
        this.responseText = responseText;
    }

    public String getResponseKind() {
        return responseKind;
    }

    public void setResponseKind(String responseKind) {
        this.responseKind = responseKind;
    }

    /**
     * Comma-separated class name of insertables, from {@link AgentResponse#getInsertables()}.
     * @return
     */
    public String getResponseInsertables() {
        return responseInsertables;
    }

    public void setResponseInsertables(String responseInsertables) {
        this.responseInsertables = responseInsertables;
    }

    /**
     * Processing time between NLP matching and immediate response.
     * @return
     */
    public Float getProcessingTime() {
        return processingTime;
    }

    public void setProcessingTime(Float processingTime) {
        this.processingTime = processingTime;
    }
}
