dialect "mvel"

import java.util.*
import org.lskk.lumen.core.*
import org.lskk.lumen.reasoner.*
import org.lskk.lumen.reasoner.event.*
import org.lskk.lumen.reasoner.expression.*
import org.lskk.lumen.reasoner.intent.*
import org.lskk.lumen.reasoner.story.*
import org.lskk.lumen.reasoner.quran.*

global org.slf4j.Logger log
global org.springframework.core.env.Environment env
global QuranService quranSvc
global LiteralRepository literalRepo
global QuranChapterRepository quranChapterRepo
global QuranVerseRepository quranVerseRepo

declare ReciteQuran
    @role( event )
end

rule "Request Recite Verse from Quran"
when
    $intent : ReciteQuran()
then
    quranSvc.recite($intent);
end
